# Generated by Django 4.2.7 on 2023-12-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_managment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='is_adming',
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.BooleanField(choices=[(False, "Regular - Can't delete members"), (True, 'Admin - Can delete members')], default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
    ]
